stages:
  - check
  - test

variables:
  MIX_ENV: test

format:
  stage: check
  image: gitlab.se.ifmo.ru:4815/veixel/functional-programming/elixir-cpp:latest
  script:
    - mix local.hex --force
    - mix local.rebar --force
    - mix deps.get
    - mix format --check-formatted

lint:
  stage: check
  image: gitlab.se.ifmo.ru:4815/veixel/functional-programming/elixir-cpp:latest
  script:
    - mix deps.get
    - mix credo --strict

test:
  stage: test
  image: gitlab.se.ifmo.ru:4815/veixel/functional-programming/elixir-cpp:latest
  script:
    - mix deps.get
    - mix test
