stages:
  - check
  - test

format:
  stage: check
  script:
    - mix local.hex --force
    - mix local.rebar --force
    - mix deps.get
    - mix format --check-formatted

# Линтер
lint:
  stage: check
  script:
    - mix deps.get
    - mix credo --strict

# Тесты
test:
  stage: test
  script:
    - mix deps.get
    - mix test
