default:
  image: elixir:1.17.2  
  before_script:
    - mix local.hex --force
    - mix local.rebar --force
    - mix deps.get  

stages:
  - check
  - test

format:
  stage: check
  script:
    - mix format --check-formatted

lint:
  stage: check
  script:
    - mix credo --strict  

test:
  stage: test
  script:
    - mix test