name: CI Pipeline  

on:
  push:
    branches: [ main ]  
  pull_request:
    branches: [ main ]  

jobs:
  check:  
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout code  
      uses: actions/checkout@v4

    - name: Set up Elixir  
      uses: erlef/setup-beam@v1
      with:
        otp-version: '27'  
        elixir-version: '1.17.2'

    - name: Cache dependencies  
      uses: actions/cache@v4
      with:
        path: |
          deps
          _build
        key: ${{ runner.os }}-elixir-${{ hashFiles('mix.lock') }}

    - name: Install dependencies  
      run: |
        mix local.hex --force
        mix local.rebar --force
        mix deps.get

    - name: Check formatting  
      run: mix format --check-formatted

    - name: Run linting  
      run: mix credo --strict

  test:  
    runs-on: ubuntu-latest
    needs: check  

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        otp-version: '27'
        elixir-version: '1.17.2'

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          deps
          _build
        key: ${{ runner.os }}-elixir-${{ hashFiles('mix.lock') }}

    - name: Install dependencies
      run: |
        mix local.hex --force
        mix local.rebar --force
        mix deps.get

    - name: Run tests  
      run: mix test
